name: Build Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build source
        run: ./gradlew build
      - name: Run Tests
        run: ./gradlew koverXmlReport
      - name: Run Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/reports/kover/report.xml
          fail_ci_if_error: true
